### PR TITLE
Remove myself from mentors

### PR DESCRIPTION
**Pull request by ghost**
After checking what's going on, I'm not sure I agree with the effort put for this project.

### CODE REVIEW

**Comment by hguemar** [comment]
@ltoscano-rh let's discuss privately about it.

**Comment by rbowen** [comment]
I would certainly like to hear your thoughts in more detail.

**Comment by duck-rh** [comment]
If this is a private matter, then I fully agree with private discussion, but if this is just a disagreement on the direction then I would like to hear about it and the community should not be shunted aside either (or they cannot participate to the discussion). We might even raise the topic in the meeting.

**Comment by hguemar** [comment]
@duck-rh let's hear what he has to say, and see with him what's the most appropriate way to move forward. We also have to consider providing safe channels for people to give their feedback, but there won't be closed door meetings about easyfix project.

**Comment by ghost** [comment]
Nothing specially secret. I understand the need to bring in new contributors and I can (and will) always help on IRC if I see the question and I know the answer (or I know who to ping for the answer).
I also understand the need to bring new people with easy task, but I have a different threshold: if it takes  way more time for me to describe a task than solve it, it's probably better if I solve it directly, and it probably does not give much value to a new contributor. At least one easyfix task was in this bucket.
The task in question touched a package that I follow so I would have seen it anyway, but with my name in the list I felt more an obligation to approve or disapprove it, and that left me a bit uneasy.
As this may be just a problem with myself and in general others may disagree on the scope and size fo items in easyfix, I prefer to remove myself from the list.

**Comment by ghost** [comment]
Also, even if I agreed to put myself to the list, I didn't do much to help the effort (adding task or preventively catching/helping people); as I don't see this changing, it's another reason to remove my name.

**Comment by rbowen** [comment]
Merging. Of course you have no obligation to be on the list.

We should be VERY clear that nothing should ever be on the EasyFix list which is in *any* way blocking. Things should only be on the list if they are "nice to have" and not at all urgent. If there's *ever* something on the list that is blocking, anyone should feel free to take it and not wait for a new contributor to take it.

**Comment by snecklifter** [comment]
@ltoscano-rh I understand where you are coming from. I made the following patch, which I think you are referencing:

https://review.rdoproject.org/r/#/c/7980/

and thought it would be quickly approved and merged but there was quite a bit (too much I think) discussion over blank lines and comments. Sorry, I didn't mean to pressure you for a review either way, I was just confused as you were. Perhaps I was thinking that some of these easyfixes would get very quick reviews and merged. I felt myself having to repeat my reasoning behind the way I just removed the comments and that, for the sake of just removing some comments, it was taking up too much time.

From my point of view, I am trying to start easy and move on to tougher assignments as I go.

**Comment by ghost** [comment]
@snecklifter this is not at all about you; you followed the task, and did all the possible things that were requested.

**Comment by snecklifter** [comment]
@ltoscano-rh thanks and thanks for all the help you have given so far, much appreciated.

**Pull request merged**
